# Generated by Django 5.2 on 2025-04-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='view_count',
            new_name='views_count',
        ),
    ]
